### ISSUE TITLE
Inicio del proyecto. Revisión de requisitos y planificación detallada

### ISSUE THREAD

**Issue by jorgeaveraf** [JoseGtz999/RutaCritica#1]
- [x] Revisión de la documentación del proyecto y los requisitos técnicos.
- [x] Creación de un plan detallado de tareas y asignación de responsables
- [x] Diseño preliminar del algoritmo PERT, definiendo variables clave (optimista, pesimista, esperado).
- [x] Definición de criterios de validación del algoritmo para asegurar la precisión.

**Comment by jorgeaveraf** [comment]
Also, we should implement the reference documentation both for the project on Google drive (administrative and operational) and introduction to the project overview, therefore we add 2 more tasks

- [x] Google drive
- [x] Introduction to repository

**Comment by jorgeaveraf** [comment]
We also need to obtain the CPM for this planification, so the task is the following:

- [x] Create CPM according with the needs of the teacher Jorge

**Comment by JoseGtz999** [comment]
Its necesary to add in the read me file the button for google drive documentation @Iker186

**Comment by Iker186** [comment]
The CPM is completed

**Comment by jorgeaveraf** [comment]
All completed, this task is closed
