### ISSUE TITLE
Desarrollo inicial del algoritmo PERT

### ISSUE THREAD

**Issue by IvanOs20** [JoseGtz999/RutaCritica#2]
- [x] Implementación del cálculo de tiempos optimistas, pesimistas y esperados.
- [x] Implementación de la fórmula de PERT considerando la desviación estándar (confianza de dos sigmas).
- [x] Validación inicial con un pequeño conjunto de datos de prueba para comprobar el cálculo correcto.
- [x] Ajustes en la lógica de cálculo según los resultados de las pruebas.

**Comment by jorgeaveraf** [comment]
All done, check it from local in Jose's computer
