### ISSUE TITLE
Desarrollo del sistema de validación de archivos CSV.

### ISSUE THREAD

**Issue by Iker186** [JoseGtz999/RutaCritica#4]
- [x] Especificación de los campos requeridos en el CSV (hitos, dependencias, tiempos).
- [x] Implementación de la validación de estructura y contenido del archivo CSV.
- [x] Documentación del proceso de validación y creación de mensajes de error claros para el usuario.

**Comment by jorgeaveraf** [comment]
All subtasks are done
