### ISSUE TITLE
Integración del algoritmo PERT con la estructura de datos de árbol eneario.

### ISSUE THREAD

**Issue by Iker186** [JoseGtz999/RutaCritica#6]
- [x] Conversión del archivo CSV en una estructura de árbol eneario para representar las dependencias.
- [x] Integración del cálculo de PERT dentro de la estructura de dependencias del árbol.
- [x] Validación de la coherencia entre el CSV y la estructura de dependencias.

**Comment by jorgeaveraf** [comment]
All substasks completed
